function random_text(){
  last_bubble = document.getElementById("text_"+bubble).innerText;
  if (last_bubble.match("Q1 of 6. What genre does this story belong to (e.g., sci-fi, realistic fiction, romance)?")){
    possible = [
      "Adventure",
      "Children's Literature",
      "Greek Mythology",
      "Comedy",
      "Cozy Mystery",
      "Crime",
      "Drama",
      "Fairy Tale",
      "Family Saga",
      "Fantasy",
      "Historical Fiction",
      "Juvenile Fiction",
      "Literary Fiction",
      "Magical Realism",
      "Middle Grade",
      "Mystery",
      "Mythology",
      "Paranormal",
      "Romantic Comedy",
      "Science Fiction",
      "Slice of Life",
      "Steampunk",
      "Superhero",
      "Suspense",
      "Thriller",
      "Time Travel",
      "Urban Fantasy",
      "Utopian",
      "Western",
      "Young Adult",
      "Adventure Fantasy",
      "Animal Fantasy",
      "Historical Mystery",
      "Folklore",
      "Contemporary Fiction",
      "Epic Fantasy",
      "Fairy Tale Retelling",
      "Historical Adventure",
      "Inspirational Romance",
      "Juvenile Adventure",
      "Middle Grade Adventure",
      "Modern Fairy Tales",
      "Mystery Thriller",
      "Paranormal Mystery",
      "Science Fantasy",
      "Science Mystery",
      "Space Opera",
      "Spy Fiction",
      "Supernatural",
      "Technothriller",
      "Traditional Fantasy",
      "Whodunit",
      "Heroic Fantasy",
      "High Fantasy",
      "Political Thriller"
    ];

    output = possible[Math.floor(Math.random() * possible.length)];
  } else if (last_bubble.match("Q2 of 6. Where does your story take place?")) {
    possible = [
      "Abandoned Castle",
      "Ancient Ruins",
      "Arctic Tundra",
      "Art Gallery",
      "Astral Plane",
      "Backyard",
      "Ballroom",
      "Bamboo Forest",
      "Beach",
      "Boarding School",
      "Boat",
      "Bookstore",
      "Botanical Garden",
      "Bus Station",
      "Cabin in the Woods",
      "Café",
      "Castle",
      "Cemetery",
      "City Park",
      "Countryside",
      "Crystal Cave",
      "Dark Forest",
      "Desert Oasis",
      "Distant Planet",
      "The Docks",
      "Dreamscape",
      "Dungeon",
      "Dystopian City",
      "Enchanted Forest",
      "Ethereal Realm",
      "Farmhouse",
      "Floating Island",
      "Garden",
      "Ghost Town",
      "Grassy Meadow",
      "Haunted House",
      "Hidden Village",
      "High School",
      "Ice Palace",
      "Island",
      "Jungle",
      "Library",
      "Lighthouse",
      "Magical Academy",
      "Medieval Village",
      "Moon Base",
      "Mountain Range",
      "Mysterious Lab",
      "Mystical Lake",
      "Ocean Depths",
      "Old Mansion",
      "Orphanage",
      "Palace",
      "Pirate Ship",
      "Pleasant Suburb",
      "Quiet Hamlet",
      "Rainforest",
      "Remote Cabin",
      "Renaissance Fair",
      "Resort",
      "Riverside",
      "Ruined Temple",
      "Safari",
      "Savannah",
      "Secluded Beach",
      "Snowy Mountain",
      "Space Station",
      "Spooky Swamp",
      "Gneration Ship (Starship)",
      "Starship",
      "Subterranean City",
      "Summer Camp",
      "Supermarket",
      "Tea House",
      "Temple",
      "Town Square",
      "Train Station",
      "Underground Lair",
      "Underwater City",
      "Urban Alleyway",
      "Utopian Society",
      "Victorian London",
      "Village Market",
      "Vineyard",
      "Warehouse",
      "Waterfall",
      "Wild West Town",
      "Wizard Tower",
      "Zoo",
      "Arcade",
      "Art Museum",
      "Asylum",
      "Bakery",
      "Ballpark",
      "Bathhouse",
      "Battlefield",
      "Beach House",
      "Bunker",
      "Bus Stop",
      "Cabin",
      "Carnival",
      "Carriage",
      "Cave",
      "Clock Tower",
      "Cottage",
      "Diner",
      "Ferris Wheel",
      "Fortress",
      "Garden Maze",
      "Glacier",
      "Graveyard",
      "Greenhouse",
      "Harbor",
      "Hospital",
      "Hotel",
      "Inn",
      "Jail",
      "Karaoke Bar",
      "Lava Field",
      "Library of Secrets",
      "Log Cabin",
      "Marketplace",
      "Maze",
      "Mountain Cabin",
      "Movie Theater",
      "Mystical Mountain",
      "Observatory",
      "Opera House",
      "Outdoor Market",
      "Pond",
      "Public Library",
      "Pyramid",
      "Rooftop",
      "Sanctuary",
      "Shipwreck",
      "Skyscraper",
      "Sports Arena",
      "Stadium",
      "Street Market",
      "Tropical Island",
      "University",
      "Waterpark",
      "Windmill",
      "Wishing Well",
      "Wooded Glade",
      "Yoga Retreat"
    ];
    output = possible[Math.floor(Math.random() * possible.length)];
  } else if (last_bubble.match("Q3 of 6. When does your story take place?")) {
    possible = [
      "Early morning",
      "Late evening",
      "Midday",
      "A prefect Summer evening",
      "A prefect Spring day",
      "A crisp Winter morning",
      "A prefect Autumn morning",
      "Fall",
      "Spring",
      "Summer",
      "Winter",
      "Prehistoric Era",
      "Ancient Greece",
      "Ancient Rome",
      "Medieval Period",
      "Renaissance",
      "Age of Exploration",
      "Industrial Revolution",
      "Victorian Era",
      "American Revolution (1776)",
      "French Revolution (1789)",
      "Civil War Era (1860s)",
      "Wild West (1865-1895)",
      "World War I (1914-1918)",
      "Roaring Twenties (1920s)",
      "Great Depression (1930s)",
      "World War II (1939-1945)",
      "Post-War Era (1950s)",
      "Civil Rights Movement (1960s)",
      "Cold War Era (1947-1991)",
      "Present Day",
      "Near Future",
      "Distant Future",
      "Far Future",
      "Apocalyptic Future",
      "Post-Apocalyptic Future",
      "Cyberpunk Future",
      "Steampunk Era",
      "Fantasy Medieval Times",
      "Space Age",
      "Era of the Galactic Empire",
      "Dinosaur Age",
      "Ice Age",
      "Iron Age",
      "Bronze Age",
      "Stone Age",
      "Age of Myth",
      "Dark Ages",
      "Enlightenment",
      "Colonial America",
      "Gilded Age",
      "Jazz Age",
      "Atomic Age",
      "Space Race Era",
      "Information Age",
      "Digital Age",
      "Feudal Japan",
      "Ming Dynasty",
      "Ancient Egypt",
      "Ancient Mesopotamia",
      "Mayan Civilization",
      "Inca Empire",
      "Mythic Past",
      "Lost Civilization",
      "Utopian Future",
      "Dystopian Future",
      "Space Colonization",
      "Age of Magic",
      "Golden Age of Piracy",
      "Viking Age",
      "Age of the Samurai",
      "Neolithic Revolution",
      "Solar Punk Future",
      "Era of the Pharaohs",
      "Peak of the Roman Empire",
      "Asteroid Mining Era",
      "Virtual Reality Age",
      "Artificial Intelligence Era",
      "Genetic Engineering Era",
      "Ancient India",
      "Sumerian Period",
      "Phoenician Era",
      "Persian Empire",
      "Hellenistic Period",
      "Gothic Era",
      "Byzantine Empire",
      "Ottoman Empire",
      "Age of Sail",
      "Era of Revolution",
      "Age of Discovery",
      "Biopunk Future",
      "Neo-Victorian Era",
      "Time of Plague",
      "Earth Reclaimed by Nature",
    ];

    output = possible[Math.floor(Math.random() * possible.length)];
  } else if (last_bubble.match("Q4 of 6. What is your character's name?")) {
    possible = [
      "Angela Foster",
      "Brian Williams",
      "Carlos Rodriguez",
      "Diana Perez",
      "Edward Clark",
      "Fiona Harris",
      "George Wilson",
      "Hannah Murphy",
      "Isaac Walker",
      "Julia Lee",
      "Kevin King",
      "Linda Scott",
      "Michael Young",
      "Natalie Allen",
      "Oscar Wright",
      "Patricia Lewis",
      "Quincy Thomas",
      "Rachel Robinson",
      "Samuel Green",
      "Theresa Mitchell",
      "Ulysses Turner",
      "Victoria Adams",
      "Walter Carter",
      "Xavier Evans",
      "Yolanda Rodriguez",
      "Zachary White",
      "Amanda Baker",
      "Brandon Campbell",
      "Carmen Brooks",
      "Daniel Reed",
      "Emily Parker",
      "Frank Kelly",
      "Gloria Sanders",
      "Henry Collins",
      "Isabella Morris",
      "Jacob Rivera",
      "Katie Diaz",
      "Liam Hill",
      "Melanie Ortiz",
      "Nathan Wood",
      "Olivia Bennett",
      "Paul Gray",
      "Quinn Jenkins",
      "Rebecca Price",
      "Steven Barnes",
      "Tina Howard",
      "Ulrich Henderson",
      "Vanessa Ward",
      "Wesley Peterson",
      "Xavier Butler",
      "Yvonne Simmons",
      "Zane Cook",
      "Alice Bell",
      "Ben Griffin",
      "Chloe Patterson",
      "David Ross",
      "Evelyn Coleman",
      "Frederick Powell",
      "Gabriella Hughes",
      "Harold James",
      "Irene Bryant",
      "Jack Alexander",
      "Kylie Russell",
      "Lucas Morgan",
      "Michelle Griffin",
      "Noah Ward",
      "Olivia Perry",
      "Patrick Martin",
      "Quinn Brooks",
      "Ryan Long",
      "Sophia Jenkins",
      "Travis Foster",
      "Ursula Rogers",
      "Vincent Russell",
      "Wendy Barnes",
      "Xavier Hughes",
      "Yasmine Morris",
      "Zander Rivera",
      "Abigail Morgan",
      "Bruce Kelly",
      "Caitlin Richardson",
      "Dylan Rogers",
      "Ethan Cooper",
      "Faith Simmons",
      "Garrett Campbell",
      "Hannah Parker",
      "Isaac Hughes",
      "Jessica Bell",
      "Kyle Sanders",
      "Leah Powell",
      "Mark Foster",
      "Nina Perry",
      "Oliver Baker",
      "Penelope Reed",
      "Quentin Mitchell",
      "Ruby Carter",
      "Scott Lewis",
      "Taylor Brooks",
      "Uma Thompson",
      "Victor White",
      "Wanda Allen",
      "Xavier Price",
      "Yolanda Bell",
      "Zane Ross",
      "Aria Nguyen",
      "Blake Johnson",
      "Cameron Kim",
      "Dakota Smith",
      "Elliot Lee",
      "Finley Martinez",
      "Grayson Patel",
      "Harper Brown",
      "Ivy Chen",
      "Jordan Davis",
      "Kai Nguyen",
      "Luca Kim",
      "Morgan Lopez",
      "Nico Singh",
      "Owen Zhang",
      "Peyton Ramirez",
      "Riley Morgan",
      "Sawyer Cruz",
      "Tatum Hill",
      "Uriah West",
      "Valentina Young",
      "Weston Green",
      "Ximena Torres",
      "Yuri Hernandez",
      "Zion Bell",
      "Aiden Carter",
      "Brooke Bailey",
      "Caden Rivera",
      "Drew Murphy",
      "Emerson Phillips",
      "Flynn Harper",
      "Genesis Clark",
      "Hayden Brown",
      "Indigo Reed",
      "Jaden Foster",
      "Kendall Brooks",
      "Logan Perry",
      "Micah Coleman",
      "Nova Lewis",
      "Orion Ross",
      "Parker Ward",
      "Quinn Robinson",
      "Reese Price",
      "Shiloh Mitchell",
      "Tanner Campbell",
      "Urban Carter",
      "Violet Hughes",
      "Wren Adams",
      "Xander Bell",
      "Yara Collins",
      "Zane Young"
    ];

    output = possible[Math.floor(Math.random() * possible.length)];
  } else if (last_bubble.match("Q5 of 6. Anything else I should know that's important to your character (e.g., age, gender, sexual orientation, physical appearance, background)?")) {
    possible = [
        "No",
        "Age: 12, Appearance: Short with freckles, Background: Middle school student.",
        "Age: 25, Appearance: Tall with dark hair, Background: Former soldier.",
        "Age: 32, Appearance: Athletic build, Background: Detective with a troubled past.",
        "Age: 19, Appearance: Short with green eyes, Background: Street performer.",
        "Age: 45, Appearance: Curly red hair, Background: Renowned scientist.",
        "Age: 28, Appearance: Muscular with tattoos, Background: Ex-convict turned chef.",
        "Age: 21, Appearance: Petite with blue hair, Background: College student.",
        "Age: 35, Appearance: Tall and lean, Background: War veteran.",
        "Age: 27, Appearance: Athletic with a scar on the cheek, Background: Pilot.",
        "Age: 23, Appearance: Slender with glasses, Background: Tech genius.",
        "Age: 30, Appearance: Medium height, blonde hair, Background: Detective.",
        "Age: 40, Appearance: Graying hair, rugged build, Background: Retired spy.",
        "Age: 26, Appearance: Androgynous, tall, Background: Artist.",
        "Age: 22, Appearance: Athletic, short hair, Background: Soccer player.",
        "Age: 31, Appearance: Dark hair, athletic, Background: Carpenter.",
        "Age: 8, Appearance: Small with curly hair, Background: Elementary school student.",
        "Age: 29, Appearance: Long dark hair, Background: Historian.",
        "Age: 24, Appearance: Tall, muscular, Background: Firefighter.",
        "Age: 37, Appearance: Average height, brunette, Background: Doctor.",
        "Age: 33, Appearance: Short and stocky, Background: Blacksmith.",
        "Age: 25, Appearance: Tall with freckles, Background: Musician.",
        "Age: 28, Appearance: Dark-skinned, dreadlocks, Background: Lawyer.",
        "Age: 36, Appearance: Tall with a strong build, Background: Mechanic.",
        "Age: 40, Appearance: Bald with a beard, Background: Fisherman.",
        "Age: 22, Appearance: Curly brown hair, Background: Journalist.",
        "Age: 34, Appearance: Fit with blue eyes, Background: Fitness trainer.",
        "Age: 27, Appearance: Slim with glasses, Background: Librarian.",
        "Age: 31, Appearance: Average height, dark eyes, Background: Architect.",
        "Age: 45, Appearance: Blonde with green eyes, Background: CEO.",
        "Age: 29, Appearance: Athletic with brown hair, Background: Bartender.",
        "Age: 24, Appearance: Short and fit, Background: Photographer.",
        "Age: 37, Appearance: Tall and broad, Background: Farmer.",
        "Age: 26, Appearance: Medium height, black hair, Background: Teacher.",
        "Age: 32, Appearance: Blond, green eyes, Background: Nurse.",
        "Age: 23, Appearance: Short with curly hair, Background: Graphic designer.",
        "Age: 30, Appearance: Average build, Background: Social Worker.",
        "Age: 35, Appearance: Tall with a beard, Background: Writer.",
        "Age: 9, Appearance: Tall for age, black hair, Background: Elementary school student.",
        "Age: 22, Appearance: Petite with piercings, Background: Dancer.",
        "Age: 29, Appearance: Muscular with blue eyes, Background: Soldier.",
        "Age: 33, Appearance: Average height, blonde, Background: Scientist.",
        "Age: 27, Appearance: Dark hair, tall, Background: Journalist.",
        "Age: 31, Appearance: Short with red hair, Background: Chef.",
        "Age: 24, Appearance: Slender with glasses, Background: Student.",
        "Age: 40, Appearance: Curly hair, average build, Background: Engineer.",
        "Age: 34, Appearance: Tall with tattoos, Background: Musician.",
        "Age: 25, Appearance: Athletic, short hair, Background: Public Defender.",
        "Age: 28, Appearance: Average height, blonde, Background: Actor.",
        "Age: 32, Appearance: Tall with green eyes, Background: Lawyer.",
        "Age: 23, Appearance: Short with black hair, Background: Programmer.",
        "Age: 29, Appearance: Tall with dark hair, Background: Architect.",
        "Age: 35, Appearance: Average height, muscular, Background: Firefighter.",
        "Age: 26, Appearance: Petite with tattoos, Background: Barista.",
        "Age: 14, Appearance: Tall for age, blond hair, Background: High school student.",
        "Age: 31, Appearance: Average height, brown hair, Background: Scientist.",
        "Age: 22, Appearance: Slender with freckles, Background: Artist.",
        "Age: 30, Appearance: Curly hair, average build, Background: Engineer.",
        "Age: 28, Appearance: Tall and lean, Background: Doctor.",
        "Age: 33, Appearance: Short with dark hair, Background: Writer.",
        "Age: 24, Appearance: Athletic with brown eyes, Background: Student.",
        "Age: 37, Appearance: Medium height, blonde, Background: CEO.",
        "Age: 26, Appearance: Short with blue eyes, Background: Photographer.",
        "Age: 29, Appearance: Tall with green eyes, Background: Historian.",
        "Age: 32, Appearance: Average height, black hair, Background: Musician.",
        "Age: 31, Appearance: Athletic with red hair, Background: MMA fighter.",
        "Age: 27, Appearance: Tall with a beard, Background: Writer.",
        "Age: 13, Appearance: Slim with brown hair, Background: Middle school student.",
        "Age: 28, Appearance: Muscular with blue eyes, Background: Soldier.",
        "Age: 34, Appearance: Tall with brown hair, Background: Scientist.",
        "Age: 26, Appearance: Athletic with tattoos, Background: Journalist.",
        "Age: 22, Appearance: Petite with brown hair, Background: Chef.",
        "Age: 30, Appearance: Tall with glasses, Background: Student.",
        "Age: 35, Appearance: Blonde with blue eyes, Background: Engineer.",
        "Age: 28, Appearance: Short with dark hair, Background: Musician.",
        "Age: 27, Appearance: Tall with a strong build, Background: Police officer.",
        "Age: 31, Appearance: Medium height, brown eyes, Background: Actor.",
        "Age: 29, Appearance: Average height, red hair, Background: Lawyer.",
        "Age: 24, Appearance: Short with black hair, Background: Programmer.",
        "Age: 10, Appearance: Short with freckles, Background: Elementary school student.",
        "Age: 50, Appearance: Gray hair, glasses, Background: High school teacher.",
        "Age: 55, Appearance: Tall with a beard, Background: Retired military officer.",
        "Age: 60, Appearance: Short with white hair, Background: Grandparent and community volunteer.",
        "Age: 48, Appearance: Average height with brown hair, Background: Small business owner.",
        "Age: 53, Appearance: Slender with green eyes, Background: Corporate executive.",
        "Age: 62, Appearance: Balding with a mustache, Background: Retired engineer.",
        "Age: 58, Appearance: Curly gray hair, Background: Librarian.",
        "Age: 65, Appearance: Tall with silver hair, Background: Retired doctor.",
        "Age: 70, Appearance: Short with a walking cane, Background: Former artist and mentor.",
        "Age: 66, Appearance: Average height with glasses, Background: Retired lawyer.",
        "Age: 72, Appearance: Tall with white beard, Background: Retired university professor."
      ];

    output = possible[Math.floor(Math.random() * possible.length)];
  } else if (last_bubble.match("Q6 of 6. Is there anything else you would like me to incorporate into the story")) {
    possible = [
      "Incorporate a strong theme of friendship.",
      "The protagonist is driven by a desire for revenge.",
      "Include a hidden treasure.",
      "Feature a rivalry with a mysterious antagonist.",
      "No.",
      "Include a pet animal with unique abilities.",
      "The protagonist is seeking redemption.",
      "Add a twist involving time travel.",
      "Incorporate elements of ancient mythology.",
      "The protagonist wants to uncover a family secret.",
      "No.",
      "The protagonist seeks to prove themselves.",
      "Include a mentor character with a mysterious past.",
      "The story should have a hopeful ending.",
      "The protagonist is motivated by love.",
      "Add a family mystery.",
      "Incorporate advanced technology in the storyline.",
      "The protagonist should have a unique magical power.",
      "The protagonist desires freedom from oppression.",
      "Include a significant dream sequence.",
      "The antagonist should have a sympathetic backstory.",
      "The protagonist wants to protect their loved ones.",
      "Feature a journey to self-discovery.",
      "Include a powerful artifact that everyone is seeking.",
      "The protagonist is searching for their true identity.",
      "Add an ancient prophecy.",
      "Incorporate a scene with a dramatic storm.",
      "The story should emphasize personal growth.",
      "The protagonist is determined to change their destiny.",
      "Include a secret underground society.",
      "The protagonist seeks justice for a wrong.",
      "Feature a character who is an expert in folklore.",
      "Include a series of puzzles or riddles to solve.",
      "The protagonist should face a moral dilemma.",
      "Incorporate a theme of redemption.",
      "The protagonist wants to fulfill a prophecy.",
      "Add a mysterious illness.",
      "The story should include a daring heist.",
      "The protagonist is driven by a need for power.",
      "Include a character with a mysterious tattoo.",
      "Incorporate elements of political intrigue.",
      "The protagonist desires to find their lost family.",
      "Feature a legendary creature.",
      "Include a forbidden romance.",
      "The protagonist is motivated by a vision or dream.",
      "Incorporate a theme of survival against the odds.",
      "The protagonist wants to break a curse.",
      "Include a character who is a master of disguise.",
      "The protagonist seeks knowledge or wisdom.",
      "Feature an ancient, lost civilization.",
      "Include a revolutionary invention.",
      "The protagonist should have a mysterious mentor.",
      "Incorporate a theme of discovering one's true self.",
      "The protagonist is driven by a vow or promise.",
      "Include a hidden message or code.",
      "The story should have an element of mystery.",
      "Add a natural disaster.",
      "The protagonist should struggle with inner demons.",
      "Incorporate a theme of betrayal and forgiveness.",
      "Feature a magical artifact with a curse.",
      "Include a character who is an outcast.",
      "The story should include a significant transformation.",
      "Incorporate a series of dreams or visions.",
      "The protagonist should uncover a hidden talent.",
      "Include a character who is a skilled musician.",
      "Add elements of espionage.",
      "The story should explore the theme of sacrifice.",
      "Incorporate a mystical guide.",
      "Include a significant betrayal.",
      "The protagonist should have to choose between two paths.",
      "Incorporate an element of horror.",
      "Feature a hidden, magical realm.",
      "Add a dark secret.",
      "Include a significant, symbolic object.",
      "The story should emphasize courage and bravery.",
      "Incorporate a journey of self-discovery.",
      "Include an ancient artifact.",
      "The protagonist should encounter an old friend.",
      "Incorporate elements of cyberpunk.",
      "The protagonist is determined to achieve their dream.",
      "The story should feature a grand adventure.",
      "No.",
      "The protagonist seeks to overcome their fears.",
      "The protagonist is on a quest for immortality.",
      "The protagonist wants to make a name for themselves.",
      "Include reconciliation with a rival.",
      "The protagonist is motivated by a mysterious benefactor.",
      "The protagonist is trying to prevent a disaster.",
      "The protagonist is searching for a lost mentor.",
      "Include a magical contract.",
      "The protagonist seeks to unite divided factions.",
      "The protagonist is trying to break a powerful enchantment.",
      "The protagonist wants to master a unique skill.",
      "Include a challenging tournament.",
      "The protagonist is haunted by past mistakes.",
      "The protagonist seeks to uncover hidden truths.",
      "Incorporate restoring honor.",
      "The protagonist wants to change societal norms.",
      "The protagonist is driven by a prophetic vision.",
      "Incorporate the theme of redemption.",
      "The protagonist is on a journey to self-discovery.",
      "Feature a powerful artifact.",
      "Include a legendary creature.",
      "The protagonist is driven by love.",
      "The protagonist wants to solve a family mystery.",
      "Add an ancient prophecy.",
      "The story should have an element of mystery.",
      "Incorporate elements of betrayal and forgiveness.",
      "The protagonist should face a moral dilemma.",
      "Include a secret underground society.",
      "The protagonist seeks to prove themselves."
    ];
    output = possible[Math.floor(Math.random() * possible.length)];
  } else {
    possible = [
      "Whatever you think my character would do.",
      "Something unexpected for my character, but that immediately makes sense once I do it.",
      "Follow my instincts.",
      "Take a bold risk.",
      "Seek out an ally.",
      "Investigate a new lead.",
      "Face a fear head-on.",
      "Reflect on recent events.",
      "Help someone in need.",
      "Make a strategic decision.",
      "Uncover a hidden truth.",
      "Protect my loved ones.",
      "Trust my intuition.",
      "Make a surprising choice.",
      "Confront my past.",
      "Take a moment to regroup.",
      "Find a way to turn the tables.",
      "Seek guidance from a mentor.",
      "Pursue a personal goal.",
      "Use my unique skills.",
      "Explore a new possibility.",
      "Defy expectations.",
      "Adapt to a sudden change.",
      "Act on a hunch.",
      "Seek redemption.",
      "Take the road less traveled.",
      "Reassess my priorities.",
      "Make a sacrifice.",
      "Follow a mysterious clue.",
      "Stand up for my beliefs.",
      "Make a quick decision.",
      "Reach out for support.",
      "Take a calculated risk.",
      "Break from routine.",
      "Push my limits.",
      "Follow a gut feeling.",
      "Act on impulse.",
      "Trust in my abilities.",
      "Seek a moment of peace.",
      "Look for an unexpected opportunity.",
      "Take decisive action.",
      "Challenge the status quo.",
      "Embrace a new perspective.",
      "Seize the initiative.",
      "Make an unconventional move.",
      "Look for a creative solution.",
      "Step outside my comfort zone.",
      "Follow a lead.",
      "Take a leap of faith.",
      "Pursue a risky venture.",
      "Seek out the truth.",
      "Find an alternative path.",
      "Take charge of the situation.",
      "Make a daring move.",
      "Reevaluate my plan.",
      "Look for hidden advantages.",
      "Take a stand.",
      "Listen to my heart.",
      "Trust my gut instinct.",
      "Surprise everyone with my decision.",
      "Revisit an old strategy.",
      "Focus on my objective.",
      "Act swiftly.",
      "Embrace the unexpected.",
      "Forge a new path.",
      "Follow a whisper of intuition.",
      "Take the initiative.",
      "Use my wits.",
      "Make a heartfelt choice.",
      "Challenge my own limits.",
      "Seek a new alliance.",
      "Take an unexpected turn.",
      "Find a clever workaround.",
      "Act decisively.",
      "Follow my heart.",
      "Look for the silver lining.",
      "Seek out wisdom.",
      "Choose the harder path.",
      "Embrace change.",
      "Take a bold step forward.",
      "Adapt quickly.",
      "Take a moment to think.",
      "Go with my gut.",
      "Surprise myself.",
      "Face the challenge head-on.",
      "Look for the next clue.",
      "Make a strategic retreat.",
      "Rely on my instincts.",
      "Seek inner strength.",
      "Take a chance.",
      "Go against the grain.",
      "Trust my feelings.",
      "Step up to the challenge.",
      "Follow the unexpected path.",
      "Consider all options.",
      "Embrace my destiny.",
      "Look within for answers.",
      "Take the lead.",
      "Listen to my inner voice.",
      "Seek a hidden opportunity.",
      "Make a bold decision.",
      "Rise to the occasion.",
      "Take a moment to breathe.",
      "Follow my dreams."
    ];
    output = possible[Math.floor(Math.random() * possible.length)];
  }

  document.getElementById('user_input').value = output;
  document.getElementById('user_input').focus();
}